# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_download', models.BooleanField(default=True, verbose_name='Can download')),
                ('can_view_content', models.BooleanField(default=True, verbose_name='Can view content')),
            ],
            options={
                'verbose_name': 'Repository User',
                'verbose_name_plural': 'Repository Users',
            },
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'Repository', 'verbose_name_plural': 'Repositories'},
        ),
        migrations.AddField(
            model_name='member',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitweb.Repository', verbose_name='Repository'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('repository', 'user')]),
        ),
    ]
